### PR TITLE
Ap/bionic deprecation

### PR DESCRIPTION
**Pull request by a-petrini**
This PR removes Ubuntu Bionic from Travis CI, as normal Long Term Support for this version will expire in May 2023.
Focal and Jammy will be the two supported version. Windows builds are performed on Focal.
Additionally, a few minor tweaking of the CI jobs and static analysis tools is performed.

### CODE REVIEW

**Review by JackPiri — APPROVED** [review]
The PR is fine to me.
Thanks

**Review by drgora — APPROVED** [review]
Looks good to me, thanks!

**Review by ptagl — COMMENTED** [review]
It looks good to me, thanks.

Should we also add one line to the release notes to warn users that we dropped official Bionic support?

**Review by cronicc — APPROVED** [review]

**Comment by cronicc** [comment]
LGTM, agree on adding a note to release notes.

**Review by ptagl — APPROVED** [review]

**Pull request merged**
