### PR TITLE
Fixed check on tx/cert validity when relaying from whitelisted peer

### PR DESCRIPTION
**Pull request by JackPiri**
This PR fixes a bug related to relaying of "AlreadyHave"-txs received from whitelisted peers.

### CODE REVIEW

**Review by drgora — APPROVED** [review]
Looks good to me, thanks

**Review by a-petrini — APPROVED** [review]
Looks good, thanks!

**Review by titusen — APPROVED** [review]
LGTM, thanks.

**Review by ptagl — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
