### PR TITLE
Update Zen References

### LINKED ISSUE #92: `Bitcoin Core` used in error message string
https://cdn.discordapp.com/attachments/334085157441110017/464114926248787979/Screen_Shot_2018-07-04_at_10.06.02_AM.png

### PR DESCRIPTION
**Pull request by hellcatz**
Update ZenCash references to resolve https://github.com/ZencashOfficial/zen/issues/92,  resolve https://github.com/ZencashOfficial/zen/issues/72, close https://github.com/ZencashOfficial/zen/pull/66

### CODE REVIEW

**Comment by hellcatz** [comment]
Should also resolve https://github.com/ZencashOfficial/zen/issues/72

**Comment by hellcatz** [comment]
I noticed some areas reference Zen, and others use ZenCash.
Should this be cleaned up to only use the term "Zen" ?

**Comment by tarrenj** [comment]
Another miner NIT: If you're going to include https://github.com/ZencashOfficial/zen/pull/66 in this PR, can you cherry pick the commits, or (rebase your branch from that PR) so that @PeaStew gets credit please?  Another option is to remove the similar fixes, and submit a new PR to `PeaStew` with the remaining reference fixes?  Basically, just follow proper [GitFlow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).

To get this merged quickly you can just remove the commits that duplicate https://github.com/ZencashOfficial/zen/pull/66.

**Review by tarrenj — CHANGES_REQUESTED** [review]
Remove commits that duplicate commits already within https://github.com/ZencashOfficial/zen/pull/66

Add a second PR to `PeaStew` branch for the fixes from this comment: https://github.com/ZencashOfficial/zen/pull/66#issuecomment-408631606

**Comment by PeaStew** [comment]
Appreciate it, would just like to see them all fixed, not fussed about "credit"

**Comment by tarrenj** [comment]
Ehh, it's more about proper GitFlow then credit. :)

**Comment by hellcatz** [comment]
Closing as requested changes have been resubmitted to PeaStew branch.

**Pull request closed without merging**
