### PR TITLE
Fixes tests closes #53

### LINKED ISSUE #53: Fix tests

### PR DESCRIPTION
**Pull request by cronicc**
* Makes full-test-suite.py work with zen
* Add fork manager test for Super/SecureNodes rewards
* Fixes make check-security

### CODE REVIEW

**Review by pierstab — APPROVED** [review]

**Review by albertog78 — APPROVED** [review]

**Comment by cronicc** [comment]
Forgot to sign my last commit, force pushed a signed amended commit.

**Comment by tarrenj** [comment]
UtACK, running tests now.

**Comment by tarrenj** [comment]
`rpc-tests.sh` output: `Failing tests: prioritisetransaction.py wallet_nullifiers.py listtransactions.py mempool_resurrect_test.py txn_doublespend.py txn_doublespend.py --mineblock getchaintips.py mempool_spendcoinbase.py mempool_coinbase_spends.py httpbasics.py proxy_test.py nodehandling.py zcjoinsplit.py zcjoinsplitdoublespend.py bip65-cltv-p2p.py bipdersig-p2p.py nulldata.py zmq_test.py`

U, I know these weren't within the scope of this PR, but I wanted to document the failures somewhere.

**Comment by tarrenj** [comment]
TestedACK, `full-test-suite.sh` passes with no failures.

**Pull request merged**
