### PR TITLE
PeaStew's patches pulled into a single PR

### PR DESCRIPTION
**Pull request by cronicc**

### CODE REVIEW

**Review by pierstab — APPROVED** [review]

**Review by albertog78 — APPROVED** [review]

**Comment by tarrenj** [comment]
UtACK, waiting until PeaStew finishes his last changes before testing and merging.

**Comment by tarrenj** [comment]
There are additional threads to rename:

```
smrtz@smrtz-VirtualBox:~$ ps -T -p 17941
  PID  SPID TTY          TIME CMD
17941 17941 pts/17   00:00:20 zend
17941 17942 pts/17   00:00:00 zcash-scriptch
17941 17943 pts/17   00:00:00 zcash-scriptch
17941 17944 pts/17   00:00:00 zcash-scriptch
17941 17945 pts/17   00:00:00 zen-scheduler
17941 17946 pts/17   00:00:00 zcash-metrics-s
17941 17947 pts/17   00:00:00 zend
17941 17948 pts/17   00:00:00 zcash-http
17941 17949 pts/17   00:00:00 zcash-httpworke
17941 17950 pts/17   00:00:00 zcash-httpworke
17941 17951 pts/17   00:00:00 zcash-httpworke
17941 17952 pts/17   00:00:00 zcash-httpworke
17941 17953 pts/17   00:00:03 zend
17941 17955 pts/17   00:00:00 zen-torcontrol
17941 17957 pts/17   00:00:00 zen-net
17941 17958 pts/17   00:00:00 zen-addcon
17941 17959 pts/17   00:00:00 zen-opencon
17941 17960 pts/17   00:00:38 zen-msghand
17941 17961 pts/17   00:00:00 zen-poolscleane
17941 17962 pts/17   00:00:00 zcash-wallet
17941 17964 pts/17   00:00:00 zen-msghand
17941 17965 pts/17   00:00:00 zen-msghand
17941 17966 pts/17   00:00:00 zen-msghand
```

**Review by tarrenj — CHANGES_REQUESTED** [review]
NIT:

If we're changing thread names, we should change them all:

```
smrtz@smrtz-VirtualBox:~$ ps -T -p 17941
  PID  SPID TTY          TIME CMD
17941 17941 pts/17   00:00:20 zend
17941 17942 pts/17   00:00:00 zcash-scriptch
17941 17943 pts/17   00:00:00 zcash-scriptch
17941 17944 pts/17   00:00:00 zcash-scriptch
17941 17945 pts/17   00:00:00 zen-scheduler
17941 17946 pts/17   00:00:00 zcash-metrics-s
17941 17947 pts/17   00:00:00 zend
17941 17948 pts/17   00:00:00 zcash-http
17941 17949 pts/17   00:00:00 zcash-httpworke
17941 17950 pts/17   00:00:00 zcash-httpworke
17941 17951 pts/17   00:00:00 zcash-httpworke
17941 17952 pts/17   00:00:00 zcash-httpworke
17941 17953 pts/17   00:00:03 zend
17941 17955 pts/17   00:00:00 zen-torcontrol
17941 17957 pts/17   00:00:00 zen-net
17941 17958 pts/17   00:00:00 zen-addcon
17941 17959 pts/17   00:00:00 zen-opencon
17941 17960 pts/17   00:00:38 zen-msghand
17941 17961 pts/17   00:00:00 zen-poolscleane
17941 17962 pts/17   00:00:00 zcash-wallet
17941 17964 pts/17   00:00:00 zen-msghand
17941 17965 pts/17   00:00:00 zen-msghand
17941 17966 pts/17   00:00:00 zen-msghand
```

**Comment by hellcatz** [comment]
PR https://github.com/ZencashOfficial/zen/pull/99
Fixes the thread naming issues.
`17941 17942 pts/17   00:00:00 zcash-scriptch`
`17941 17949 pts/17   00:00:00 zcash-httpwork`
`17941 17962 pts/17   00:00:00 zcash-wallet`
`17941 17948 pts/17   00:00:00 zcash-http`
`17941 17946 pts/17   00:00:00 zcash-metrics-s`
`17941 17946 pts/17   00:00:00 zcash-miner`

It also updates a lot more Zen references.

**Comment by hellcatz** [comment]
PR https://github.com/ZencashOfficial/zen/pull/99 should be merged into this PR before it is merged.

**Review by tarrenj — APPROVED** [review]

**Comment by tarrenj** [comment]
UtACK, will test today.

**Comment by tarrenj** [comment]
https://github.com/ZencashOfficial/zen/pull/101 must be merged before this.

**Review by albertog78 — APPROVED** [review]

**Pull request merged**
