### PR TITLE
Prepare release/4.1.0 beta1

### PR DESCRIPTION
**Pull request by JackPiri**
Tag v4.0.0-beta3 (commits from 70fb078c6dc33586c12005334a23aea7fbf7044c to c3b6d2942d5d692119e633a919907e972cfb9045) has been considered as a reference.
Branch created with latest version of release preparation script.
Used beta1 as build number but final tag will be marked as 4.1.0-wip1.

### CODE REVIEW

**Review by ptagl — APPROVED** [review]
Looks good to me, thanks! As a minor comment, release notes may not be fully up to date, but it's not a big deal considering that this is just a WIP release for testing purposes.

**Review by cronicc — APPROVED** [review]
LGTM, are planning for this code to ever end up in the main branch (I don't think that would be a good idea)?

**Comment by JackPiri** [comment]
> LGTM, are planning for this code to ever end up in the main branch (I don't think that would be a good idea)?

No, there will be no backporting of this branch into `main` (just consider this as a temporary release for testing purpose).

**Comment by JackPiri** [comment]
> Looks good to me, thanks! As a minor comment, release notes may not be fully up to date, but it's not a big deal considering that this is just a WIP release for testing purposes.

Release notes file updated (actually just inserted a reference to PR #555).

**Pull request merged**
