### PR TITLE
Update Centos build instructions

### PR DESCRIPTION
**Pull request by greerso**
Update Centos Build instructions with GCC 4.9 dependency to resolve issue #131

### CODE REVIEW

**Comment by tarrenj** [comment]
UtACK, will build a new CentOS vm to test now.

**Comment by tarrenj** [comment]
Blocking NIT: Please include the other updates we talked about in Discord.

u. Resolved.

**Review by greerso — COMMENTED** [review]
Updated Centos build instructions per https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html#installation

**Review by greerso — COMMENTED** [review]
Added installing required 'Development Tools' group for Centos

**Review by greerso — COMMENTED** [review]
Remove wget from centos build instructions.  Not a dependency

**Review by greerso — COMMENTED** [review]
Added missing git clone to install instructions

**Review by tarrenj — DISMISSED** [review]
TestedACK

**Review by greerso — COMMENTED** [review]
Tested on Centos 6 and 7.  Build fails on 6.  Centos 7 required.

**Comment by tarrenj** [comment]
~~Please change line 34 to `2. CentOS 7 (CentOS 6 is unsupported):`~~

u. Actually, it's fine as it is. Thanks!

**Review by tarrenj — APPROVED** [review]

**Comment by tarrenj** [comment]
TestedACK. Waiting on @cronicc to verify dependencies before merging.

**Comment by greerso** [comment]
Reopening pr per @tarrenj request

**Pull request merged**
