### PR TITLE
Fix build with gcc10

### LINKED ISSUE #322: Not compiling with gcc 10
In file included from crypto/equihash.cpp:20:
./crypto/equihash.h: In function ‘bool EhBasicSolve(unsigned int, unsigned int, const eh_HashState&, std::function<bool(std::vector)>, std::function<bool(EhSolverCancelCheck)>)’:
./crypto/equihash.h:230:20: error: ‘invalid_argument’ is not a member of ‘std’
230 | throw std::invalid_argument("Unsupported Equihash parameters");
| ^~~~~~~~~~~~~~~~
./crypto/equihash.h: In function ‘bool EhOptimisedSolve(unsigned int, unsigned int, const eh_HashState&, std::function<bool(std::vector)>, std::function<bool(EhSolverCancelCheck)>)’:
./crypto/equihash.h:254:20: error: ‘invalid_argument’ is not a member of ‘std’
254 | throw std::invalid_argument("Unsupported Equihash parameters");
| ^~~~~~~~~~~~~~~~
make[2]: *** [Makefile:3046: crypto/libbitcoin_crypto_a-equihash.o] Error 1

About this:
https://gcc.gnu.org/gcc-10/porting_to.html#common

Pull request to fix this: https://github.com/HorizenOfficial/zen/pull/321

### PR DESCRIPTION
**Pull request by fellu**
fixes #322

In file included from crypto/equihash.cpp:20:
./crypto/equihash.h: In function ‘bool EhBasicSolve(unsigned int, unsigned int, const eh_HashState&, std::function<bool(std::vector<unsigned char>)>, std::function<bool(EhSolverCancelCheck)>)’:
./crypto/equihash.h:230:20: error: ‘invalid_argument’ is not a member of ‘std’
  230 |         throw std::invalid_argument("Unsupported Equihash parameters");
      |                    ^~~~~~~~~~~~~~~~
./crypto/equihash.h: In function ‘bool EhOptimisedSolve(unsigned int, unsigned int, const eh_HashState&, std::function<bool(std::vector<unsigned char>)>, std::function<bool(EhSolverCancelCheck)>)’:
./crypto/equihash.h:254:20: error: ‘invalid_argument’ is not a member of ‘std’
  254 |         throw std::invalid_argument("Unsupported Equihash parameters");
      |                    ^~~~~~~~~~~~~~~~
make[2]: *** [Makefile:3046: crypto/libbitcoin_crypto_a-equihash.o] Error 1

https://gcc.gnu.org/gcc-10/porting_to.html#common

### CODE REVIEW

**Comment by fellu** [comment]
Can this be merged? :3

**Review by cronicc — APPROVED** [review]
Tested ACK, Ubuntu 20.10 with gcc10 works.

**Review by abi87 — CHANGES_REQUESTED** [review]
Hello @fellu . 
First off, apologies if it took us so long to get to your PR.
We checked it and it's fine with two exceptions:
1. Once `<stdexcept>` header is duly included, the `<exception>` one can be removed. Could you do that?
2. Our dev cycle is to target the branch `development` for every PR. Later on `development` is merged into `master` by our ops guys in order to generate official releases, binaries and so forth. Could you edit your PR to target  `development`?

Other than these minor changes, I do not see problem in approving the PR, in a much more expeditious way than we have done so far.
Thanks!

**Comment by cronicc** [comment]
@fellu we've incorporated your commit into a PR which is going to get merged for the upcoming 2.0.22 release.

**Pull request closed without merging**
