### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by preserveddarnell**
Minor edits.

### CODE REVIEW

**Comment by tarrenj** [comment]
Thanks for the PR!  Please resubmit this with the target branch of `development`, and I'll merge it.

**Comment by preserveddarnell** [comment]
> Thanks for the PR! Please resubmit this with the target branch of `development`, and I'll merge it.

Is there an easier way that I can change the target branch to resubmit?

**Comment by tarrenj** [comment]
I just knocked it out for you. You click the `Edit` button in the top right and then you can change it within this PR.

**Review by tarrenj — APPROVED** [review]
LGTM, merging.

**Pull request merged**
